
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: localhost

development:
  <<: *default
  database: grammable2_development

test:
  <<: *default
  database: grammable2_test

production:
  <<: *default
  database: grammable2_production
  ## username: grammable2
  ## password: <%= ENV['GRAMMABLE2_DATABASE_PASSWORD'] %>
